config/routes.rb
  get   '(/user/:user_domain)(/u/:user_domain)/signup_http_authentication' => 'signup#create_http_authentication', as: :signup_http_authentication
  get   '(/user/:user_domain)(/u/:user_domain)/signup_http_authentication_in_progress' => 'signup#create_http_authentication_in_progress', as: :signup_http_authentication_in_progress

  get   '(/user/:user_domain)(/u/:user_domain)/enable_account_token/:id' => 'account_tokens#enable',     as: :enable_account_token_show
  get   '(/user/:user_domain)(/u/:user_domain)/resend_validation_mail/:user_id' => 'account_tokens#resend',     as: :resend_validation_mail
  get   '(/user/:user_domain)(/u/:user_domain)/account_token_authentication_error' => 'sessions#account_token_authentication_error',     as: :account_token_authentication_error

  get   '(/user/:user_domain)/login' => 'sessions#new',     as: :login
  match '(/user/:user_domain)(/u/:user_domain)/logout'          => 'sessions#destroy', as: :logout, via: [:get, :post]
  match '(/user/:user_domain)(/u/:user_domain)/sessions/create' => 'sessions#create',  as: :create_session, via: [:get, :post]
  get '(/user/:user_domain)(/u/:user_domain)/multifactor_authentication' => 'sessions#multifactor_authentication',  as: :multifactor_authentication_session
  post '(/user/:user_domain)(/u/:user_domain)/multifactor_authentication' => 'sessions#multifactor_authentication_verify_code',  as: :multifactor_authentication_verify_code

  get '(/user/:user_domain)(/u/:user_domain)/status'          => 'home#app_status'
  get '(/user/:user_domain)(/u/:user_domain)/diagnosis'       => 'home#app_diagnosis'

  # Password change
  resources :password_change, only: [:edit, :update]

  # Password resets
  get '(/user/:user_domain)(/u/:user_domain)/password_resets/new'         => 'password_resets#new',      as: :new_password_reset
  post '(/user/:user_domain)(/u/:user_domain)/password_resets'            => 'password_resets#create',   as: :create_password_reset
  get '(/user/:user_domain)(/u/:user_domain)/password_resets/:id/edit'    => 'password_resets#edit',     as: :edit_password_reset
  match '(/user/:user_domain)(/u/:user_domain)/password_resets/:id/edit'  => 'password_resets#update',   as: :update_password_reset, via: [:put, :patch]
  get '(/user/:user_domain)(/u/:user_domain)/password_resets/sent'        => 'password_resets#sent',     as: :sent_password_reset
  get '(/user/:user_domain)(/u/:user_domain)/password_resets/changed'     => 'password_resets#changed',  as: :changed_password_reset

  # Data library
  get   '(/user/:user_domain)(/u/:user_domain)/data-library'           => 'data_library#index',     as: :data_library_index

  # OAuth
  match '(/user/:user_domain)(/u/:user_domain)/oauth/authorize'      => 'oauth#authorize',     as: :authorize, via: [:get, :post]
  match '(/user/:user_domain)(/u/:user_domain)/oauth/request_token'  => 'oauth#request_token', as: :request_token, via: [:get, :post]
  match '(/user/:user_domain)(/u/:user_domain)/oauth/access_token'   => 'oauth#access_token',  as: :access_token, via: [:get, :post]
  get   '(/user/:user_domain)(/u/:user_domain)/oauth/identity'       => 'sessions#show',       as: :oauth_show_sessions

  # This is what an external SAML endpoint should redirect to after successful auth.
  post '(/user/:user_domain)(/u/:user_domain)/saml/finalize' => 'sessions#create'

  # Editor v3
  scope module: 'carto', path: '(/user/:user_domain)(/u/:user_domain)' do
    namespace :builder, path: '/' do
      # Visualizations
      resources :visualizations, only: :show, path: '/builder', constraints: { id: /[0-z\.\-]+/ } do
        namespace :public, path: '/' do
          match 'embed', to: 'embeds#show', via: :get
          match 'embed_protected', to: 'embeds#show_protected', via: :post
          match 'embed_protected', to: 'embeds#show', via: :get
        end
      end

      match '/builder/:id/*other', to: 'visualizations#show', via: :get

      resources :datasets, path: '/dataset', only: :show, constraints: { id: /[0-z\.\-]+/ }
    end

    namespace :editor do
      get '(*path)', to: redirect { |params, request|
        CartoDB.base_url_from_request(request) + '/builder/' + params[:path].to_s
      }
    end

    get '/github' => 'oauth_login#github', as: :github
    get '/google/oauth' => 'oauth_login#google', as: :google_oauth
    get '/saml/metadata' => 'saml#metadata'

    # Oauth2 provider
    get  '/oauth2/authorize', to: 'oauth_provider#consent', as: :oauth_provider_authorize
    post '/oauth2/authorize', to: 'oauth_provider#authorize'
    post '/oauth2/token',     to: 'oauth_provider#token', as: :oauth_provider_token

    namespace :kuviz, path: '/' do
      # Custom Visualizations
      match '/kuviz/:id', to: 'visualizations#show', via: :get, as: :show
      match '/kuviz/:id/protected', to: 'visualizations#show_protected', via: :post, as: :password_protected
      match '/kuviz/:id/protected', to: 'visualizations#show', via: :get
    end
  end

  # Internally, some of this methods will forcibly rewrite to the org-url if user belongs to an organization
  scope :module => :admin do

    # Organization dashboard page
    get    '(/user/:user_domain)(/u/:user_domain)/organization'                 => 'organizations#show',            as: :organization
    delete '(/user/:user_domain)(/u/:user_domain)/organization'                 => 'organizations#destroy',          as: :organization_destroy
    get    '(/user/:user_domain)(/u/:user_domain)/organization/settings'        => 'organizations#settings',        as: :organization_settings
    match  '(/user/:user_domain)(/u/:user_domain)/organization/settings'        => 'organizations#settings_update', as: :organization_settings_update, via: [:put, :patch]
    post '(/user/:user_domain)(/u/:user_domain)/organization/regenerate_api_keys'       => 'organizations#regenerate_all_api_keys', as: :regenerate_organization_users_api_key

    get    '(/user/:user_domain)(/u/:user_domain)/organization/groups(/*other)' => 'organizations#groups',          as: :organization_groups

    get    '(/user/:user_domain)(/u/:user_domain)/organization/auth'        => 'organizations#auth',        as: :organization_auth
    match  '(/user/:user_domain)(/u/:user_domain)/organization/auth'        => 'organizations#auth_update', as: :organization_auth_update, via: [:put, :patch]

    get    '(/user/:user_domain)(/u/:user_domain)/organization/notifications' => 'organizations#notifications',          as: :organization_notifications_admin
    post   '(/user/:user_domain)(/u/:user_domain)/organization/notifications' => 'organizations#new_notification',          as: :new_organization_notification_admin
    delete '(/user/:user_domain)(/u/:user_domain)/organization/notifications/:id' => 'organizations#destroy_notification',          as: :destroy_organization_notification_admin

    # Organization users management
    get '(/user/:user_domain)(/u/:user_domain)/organization/users/:id/edit'  => 'organization_users#edit',    as: :edit_organization_user,   constraints: { id: /[0-z\.\-]+/ }
    match '(/user/:user_domain)(/u/:user_domain)/organization/users/:id'       => 'organization_users#update',  as: :update_organization_user, constraints: { id: /[0-z\.\-]+/ }, via: [:put, :patch]
    get '(/user/:user_domain)(/u/:user_domain)/organization/users'                 => 'organizations#show',            as: :organization_users
    post '(/user/:user_domain)(/u/:user_domain)/organization/users'           => 'organization_users#create',  as: :create_organization_user
    delete '(/user/:user_domain)(/u/:user_domain)/organization/users/:id'       => 'organization_users#destroy', as: :delete_organization_user, constraints: { id: /[0-z\.\-]+/ }
    post '(/user/:user_domain)(/u/:user_domain)/organization/users/:id/regenerate_api_key'       => 'organization_users#regenerate_api_key', as: :regenerate_organization_user_api_key, constraints: { id: /[^\/]+/ }
    get '(/user/:user_domain)(/u/:user_domain)/organization/users/new'       => 'organization_users#new',     as: :new_organization_user

    # User profile and account pages
    get    '(/user/:user_domain)(/u/:user_domain)/profile' => 'users#profile',        as: :profile_user
    get    '(/user/:user_domain)(/u/:user_domain)/account' => 'users#account',        as: :account_user
    get    '(/user/:user_domain)(/u/:user_domain)/dashboard/oauth_apps' => 'visualizations#index', as: :oauth_apps_user
    get    '(/user/:user_domain)(/u/:user_domain)/dashboard/oauth_apps/new' => 'visualizations#index', as: :oauth_apps_user_new
    get    '(/user/:user_domain)(/u/:user_domain)/dashboard/oauth_apps/edit/:id' => 'visualizations#index', as: :oauth_apps_user_edit
    get    '(/user/:user_domain)(/u/:user_domain)/dashboard/connected_apps' => 'visualizations#index', as: :connected_apps_user

    # Lockout
    get '(/user/:user_domain)(/u/:user_domain)/lockout' => 'users#lockout', as: :lockout

    # Maintenance Mode
    get '(/user/:user_domain)(/u/:user_domain)/maintenance_mode' => 'users#maintenance', as: :maintenance_mode

    # search
    get '(/user/:user_domain)(/u/:user_domain)/dashboard/search/:q'               => 'visualizations#index', as: :search
    get '(/user/:user_domain)(/u/:user_domain)/dashboard/search/tag/:q'           => 'visualizations#index', as: :tag_search
    get '(/user/:user_domain)(/u/:user_domain)/dashboard/search/:q/:page'         => 'visualizations#index', as: :search_page
    get '(/user/:user_domain)(/u/:user_domain)/dashboard/shared/search/:q'        => 'visualizations#index', as: :search_shared
    get '(/user/:user_domain)(/u/:user_domain)/dashboard/shared/search/:q/:page'  => 'visualizations#index', as: :search_shared_page

    # Tables
    get '(/user/:user_domain)(/u/:user_domain)/dashboard/tables'                            => 'visualizations#index', as: :tables_index
    get '(/user/:user_domain)(/u/:user_domain)/dashboard/tables/:page'                      => 'visualizations#index', as: :tables_page

app/models/visualization/derived_creator.rb
module CartoDB
  module Visualization
    class DerivedCreator
      DEFAULT_MAP_NAME = 'Untitled Map'

      def initialize(user, tables = [])
        @rejected_layers = []

        if tables.length > user.max_layers
          tables.pop(tables.length - user.max_layers).each do |rejected_layers|
            @rejected_layers << rejected_layers.name
          end
        end

        @user   = user
        @tables = tables
      end

      def create
        blender = CartoDB::Visualization::TableBlender.new(user, tables)
        map = blender.blend

        vis = Carto::Visualization.new(
          name: beautify_name,
          map_id: map.id,
          type: Carto::Visualization::TYPE_DERIVED,
          privacy: blender.blended_privacy,
          user_id: user.id
        )
        unless user.private_maps_enabled
          vis.privacy = Carto::Visualization::PRIVACY_PUBLIC
        end

        vis.save!
        CartoDB::Visualization::Overlays.new(vis).create_default_overlays

        [vis, @rejected_layers]
      end

      private

      def beautify_name
        if tables.length > 1
          table = tables[0]
          table.beautify_name(table.name)
        else
          DEFAULT_MAP_NAME
        end
      end

      attr_reader :user, :tables, :rejected_layers
    end
  end
end

app/models/visualization/external_source.rb
require 'sequel'
require_relative './member'

module CartoDB
  module Visualization

    class ExternalSource < Sequel::Model
      many_to_one :visualization

      def validate
        validates_presence :visualization_id
        validates_presence :import_url
        # TODO: retrieve geometry_types
        #validates_presence :geometry_types
        validates_presence :rows_counted
        validates_presence :size
      end

      def initialize(visualization_id, import_url, geometry_types, rows_counted, size, username = nil)
        super({ visualization_id: visualization_id, import_url: import_url, geometry_types: geometry_types, rows_counted: rows_counted, size: size, username: username })
      end

      def importable_by?(user)
        user.present? && visualization.user_id == user.id
      end

      def visualization
        @visualization ||= CartoDB::Visualization::Member.new(id: visualization_id).fetch
      end

    end
  end
end

app/models/visualization/like.rb
module CartoDB
  class Like < Sequel::Model

    # PK is (actor,subject)
    unrestrict_primary_key

    # @param actor String (uuid)
    # @param subject String (uuid)
    # @param created_at DateTime

  end

  class AlreadyLikedError < StandardError; end
end

app/models/visualization/name_checker.rb
require_relative './collection'

module CartoDB
  module Visualization
    class NameChecker
      def initialize(user)
        @user = user
      end

      def available?(candidate)
        !taken_names_for.include?(candidate)
      end

      private

      def taken_names_for
        @taken_names ||= Carto::Visualization::where(user_id: user.id).select(:name).map(&:name)
      end

      attr_reader :user
    end # NameChecker
  end # Visualization
end # CartoDB

app/models/visualization/name_generator.rb
require_relative './name_checker'

module CartoDB
  module Visualization
    class NameGenerator
      PATTERN = 'Untitled map'

      def initialize(user, checker=nil)
        @user     = user
        @checker  = checker || NameChecker.new(user)
      end

      def name(candidate=PATTERN, iteration=0)
        candidate = (candidate || PATTERN).strip
        new_candidate = iteration > 0 ? "#{candidate} #{iteration}" : candidate
        return new_candidate if checker.available?(new_candidate)

        name(candidate, iteration + 1)
      end

      private

      attr_reader :checker, :user
    end
  end
end

app/controllers/carto/builder/visualizations_controller.rb
require 'carto/api/vizjson3_presenter'
require 'carto/api/layer_presenter'

require_dependency 'carto/tracking/events'
require_dependency 'carto/visualization_migrator'

module Carto
  module Builder
    class VisualizationsController < BuilderController
      include VisualizationsControllerHelper
      include Carto::VisualizationMigrator

      ssl_required :show

      before_filter :load_derived_visualization,
                    :redirect_to_editor_if_forced,
                    :auto_migrate_visualization_if_possible, only: :show
      before_filter :authors_only
      before_filter :editable_visualizations_only, :load_carto_viewer, only: :show

      # TODO: remove this when analysis logic lives in the backend
      before_filter :ensure_source_analyses, unless: :has_analyses?

      after_filter :update_user_last_activity,
                   :track_builder_visit, only: :show

      layout 'application_builder'

      def show
        @visualization_data = Carto::Api::VisualizationPresenter.new(@visualization, current_viewer, self).to_poro
        @layers_data = @visualization.layers.map do |l|
          Carto::Api::LayerPresenter.new(l, with_style_properties: true).to_poro(migrate_builder_infowindows: true)
        end
        @vizjson = generate_anonymous_map_vizjson3(@visualization)
        @state = @visualization.state.json
        @analyses_data = @visualization.analyses.map { |a| Carto::Api::AnalysisPresenter.new(a).to_poro }
        @basemaps = current_viewer.basemaps
        @overlays_data = @visualization.overlays.map do |overlay|
          Carto::Api::OverlayPresenter.new(overlay).to_poro
        end
        latest_mapcap = @visualization.latest_mapcap
        @mapcaps_data = latest_mapcap ? [Carto::Api::MapcapPresenter.new(latest_mapcap).to_poro] : []
        @google_maps_qs = @visualization.user.google_maps_query_string

        @builder_notifications = notifications(:builder)
        @dashboard_notifications = notifications(:dashboard)
      end

      private

      def load_carto_viewer
        @carto_viewer = current_viewer && Carto::User.where(id: current_viewer.id).first
      end

      def notifications(category)
        @carto_viewer ? @carto_viewer.notifications_for_category(category) : {}
      end

      def redirect_to_editor_if_forced
        if !current_user.builder_enabled? || @visualization.open_in_editor?
          redirect_to CartoDB.url(self, 'public_visualizations_show_map', params: { id: params[:id] },
                                                                          user: current_user)
        end
      end

      def load_derived_visualization
        @visualization = load_visualization_from_id_or_name(params[:id])
        render_404 unless @visualization && @visualization.derived?
      end

      def authors_only
        unauthorized unless !current_user.nil? && @visualization.writable_by?(current_user)
      end

      def editable_visualizations_only
        render_404 unless @visualization.editable?
      end

      def has_analyses?
        @visualization.analyses.any?
      end

      def ensure_source_analyses
        @visualization.add_source_analyses
        @visualization.reload
      end

      def unauthorized
        redirect_to CartoDB.url(self, 'builder_visualization_public_embed',
                                params: { visualization_id: request.params[:id] })
      end

      def track_builder_visit
        current_viewer_id = current_viewer.id
        Carto::Tracking::Events::VisitedPrivatePage.new(current_viewer_id,
                                                        user_id: current_viewer_id,
                                                        page: 'builder').report
      end

      def auto_migrate_visualization_if_possible
        if version_needs_migration?(@visualization.version, 3) && @visualization.can_be_automatically_migrated_to_v3?
          @visualization.version = 3
          @visualization.save
          migrate_visualization_to_v3(@visualization)
        end
      end
    end
  end
end

app/views/admin/visualizations/embed_map.html.erb
<% require_dependency 'static_maps_url_helper' %>

<%= content_for(:title) do %><%= @visualization.name %><% end %>

<%= content_for(:description) do %><%= @visualization.description.present? ? "#{markdown_html_clean(@visualization.description)}. Map created by #{@name} in CARTO" : "Map created by #{@name} in CARTO" %><% end %>

<%= content_for(:twitter_card) do %><%= Carto::StaticMapsURLHelper.new.url_for_static_map(request, @visualization, 560, 300) %><% end %>
<%= content_for(:facebook_card) do %><%= Carto::StaticMapsURLHelper.new.url_for_static_map(request, @visualization, 1200, 630) %><% end %>

<%= content_for(:css) do %>
  <%= render :partial => 'admin/visualizations/public/embed_map_inline_css' %>
<% end %>

<%= content_for(:body_class) do %>
  embed-map
<% end %>

<%= content_for(:content) do %>
  <% if @visualization.public? || @visualization.public_with_link? || @visualization.password_protected? || @visualization.organization? %>
    <div id="map"></div>

    <div id="not_supported_dialog" style="display: none">
      <h2>CARTO</h2>
      <p>This visualization only works in modern browsers. Upgrade yours and enjoy.</p>
      <ul>
        <li><a href="http://www.apple.com/safari/" class="safari">Safari</a></li>
        <li><a href="https://www.google.com/chrome/" class="chrome">Chrome</a></li>
        <li class="last"><a href="http://www.mozilla.org/en-US/firefox/all/‎" class="firefox">Firefox</a></li>
      </ul>
    </div>

    <div class="cartodb-text">
      Map created by
      <% username = @visualization.user.name_or_username %>
      <a class="user" href="<%= CartoDB.url(self, 'public_user_feed_home', user: @visualization.user) %>?utm_source=Footer_Link&utm_medium=referral&utm_campaign=Embed_v1&utm_content=<%= @visualization.user.username %>" target="_blank">
        <% if !@visualization.user.avatar_url.blank? %>
          <img src="<%= @visualization.user.avatar_url %>" width="16" height="16" alt="<%= username %>" title="<%= username %>" />
        <% end %>
        <span class="username"><%= username %></span>
      </a>
    </div>
  <% end %>
<% end %>

<%= content_for(:js) do %>
  <%= insert_trackjs('embeds', Cartodb.get_config(:trackjs, 'frequency')) %>
  <%= render :partial => 'admin/visualizations/public/embed_map_inline_js' %>
<% end %>

app/views/admin/visualizations/embed_map_error.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Embed error | CARTO</title>
    <%= editor_stylesheet_link_tag 'password_protected.css' %>
    <%= insert_google_tag_manager('embeds') %>
  </head>

  <body class='PublicPage-body PublicPage-background--grey'>
    <%= insert_google_tag_manager_no_script('embeds') %>
    <div class='PublicPage-centerContainer'>
      <div class='PublicPage-container'>
        <div class='PublicPage-protectedEmbed-iconContainer'>
          <svg version="1.1" id="Outline_Icons" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50px" height="50px" viewBox="0 0 24 24">
            <g id="Editor-private-embed" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
              <path fill='#27353C' d="M17.479,11.035c-3.584,0-6.5,2.916-6.5,6.5s2.916,6.5,6.5,6.5s6.5-2.916,6.5-6.5S21.062,11.035,17.479,11.035z
                 M17.479,23.035c-3.033,0-5.5-2.467-5.5-5.5s2.467-5.5,5.5-5.5s5.5,2.467,5.5,5.5S20.511,23.035,17.479,23.035z"/>
              <circle fill='#27353C' cx="17.479" cy="20.802" r="0.593"/>
              <path fill='#27353C' d="M17.479,13.484c-1.256,0-2.277,1.022-2.277,2.278c0,0.276,0.224,0.5,0.5,0.5s0.5-0.224,0.5-0.5
                c0-0.705,0.573-1.278,1.277-1.278c0.706,0,1.279,0.573,1.279,1.278c0,0.705-0.574,1.278-1.279,1.278c-0.276,0-0.5,0.224-0.5,0.5
                v1.779c0,0.276,0.224,0.5,0.5,0.5s0.5-0.224,0.5-0.5v-1.334c1.017-0.229,1.779-1.138,1.779-2.223
                C19.758,14.506,18.735,13.484,17.479,13.484z"/>
              <path fill='#27353C' d="M1,1h10v4.5C11,5.776,11.224,6,11.5,6H16v4h1V5.5c0-0.067-0.014-0.132-0.039-0.192c-0.025-0.061-0.062-0.116-0.108-0.162
                l-4.999-4.999c-0.046-0.046-0.101-0.083-0.162-0.108C11.632,0.014,11.567,0,11.5,0h-11C0.224,0,0,0.224,0,0.5v21
                C0,21.776,0.224,22,0.5,22H11v-1H1V1z M12,1.707L15.293,5H12V1.707z"/>
            </g>
          </svg>
        </div>

        <p class='CDB-Text CDB-Size-large'>
          Map or dataset not found, or with restricted access. Please <%= link_to "login", login_url(after: request.original_url), target: "_blank" %> to your account and try again
        </p>
      </div>
    </div>

  </body>
</html>

app/views/admin/visualizations/embed_map_error.js.erb
(function() {

    function get_url_params(url, conversion) {
      conversion = conversion || {};
      if(!url) {
        return {};
      }
      var search = url.split('?');
      if(search.length < 2) {
        return {};
      }
      search = search[1];
      var tokens = search.split('&');
      var params = {};
      for(var i = 0; i < tokens.length; ++i) {
        var tk = tokens[i].split('=');
        var fn = conversion[tk[0]] || function(v) { return v };
        if(tk.length === 2) {
          params[tk[0]] = fn(decodeURIComponent(tk[1]));
        }
      }
      return params;
    }
    
    var url = location.search;
    var opt = get_url_params(url);

    var height = opt.height || '400';
    if(height.indexOf('%') == -1)  {
      height += 'px';
    }

    var l = document.createElement("a");
    l.href = url
    if(l.protocol.indexOf('http') != -1) {
        var port = l.port ? ':' + l.port: '';
        document.write('<iframe src="' + l.protocol + '//' + l.hostname + port + '/viz/embed_forbidden" frameborder="0" width="100%" height="' + height +'" ></iframe>');
    }

})();

app/views/admin/visualizations/embed_map_password.html.erb
<%= content_for(:title) do %>
  Protected embed
<% end %>

<%= content_for(:header_title) do %>
  This embed is protected with password
<% end %>

<%= content_for(:password_form) do %>
  <%= form_tag(CartoDB.url(self, 'protected_embed_map', params: { :protocol => Rails.env.development? ? 'http' : 'https' }) + '?' + request.query_string, {:method=>'POST',:authenticity_token=>false}) do %>

    <div class='PublicPage-field-withTooltip'>
      <%= password_field_tag 'password', params[:password], class: "PublicPage-form--inputText RoundBorders-all CDB-Text CDB-Size-medium is-light u-whiteTextColor #{ flash[:error].present? ? 'is-alert' : ''}", placeholder: 'Insert your password'%>

      <%- if flash[:error].present? %>
        <div class="PublicPage-inputTooltip CDB-InfoTooltip CDB-InfoTooltip--left u-lSpace--xl is-error">
          <p class='CDB-Text CDB-Size-medium CDB-InfoTooltip-text'><%= flash[:error] %></p>
        </div>
      <% end %>
    </div>

  <% end %>
<% end %>

<%= content_for(:ua) do %>
  embeds
<% end %>

app/views/admin/visualizations/public_map_password.html.erb
<%= content_for(:title) do %>
  Protected map
<% end %>

<%= content_for(:header_title) do %>
  This map is protected with password
<% end %>

<%= content_for(:password_form) do %>
  <%= form_tag(CartoDB.url(self, 'protected_public_map', params: { :protocol => Rails.env.development? ? 'http' : 'https'}) + '?' + request.query_string, { :method => 'POST', :authenticity_token => false}) do %>

    <div class='PublicPage-field-withTooltip'>
      <%= password_field_tag 'password', params[:password], class: "PublicPage-form--inputText RoundBorders-all CDB-Text CDB-Size-medium is-light u-whiteTextColor #{ flash[:error].present? ? 'is-alert' : ''}", placeholder: 'Insert your password'%>

      <%- if flash[:error].present? %>
        <div class="PublicPage-inputTooltip CDB-InfoTooltip CDB-InfoTooltip--left u-lSpace--xl is-error">
          <p class='CDB-Text CDB-Size-medium CDB-InfoTooltip-text'><%= flash[:error] %></p>
        </div>
      <% end %>
    </div>

  <% end %>
<% end %>

<%= content_for(:ua) do %>
  primary
<% end %>

app/views/admin/visualizations/show.html.erb
  <% content_for(:page_title) do %>
    <%= @visualization.name %> |
  <% end %>

  <% content_for(:css) do %>
    <%= editor_stylesheet_link_tag  'old_common_without_core.css', 'common.css', 'cdb.css', 'table.css', 'editor.css', 'map.css', :media => 'all' %>
  <% end %>

  <script type="text/javascript" id="dropboxjs" src="//www.dropbox.com/static/api/1/dropins.js" data-app-key="<%= Cartodb.config[:dropbox_api_key] %>"></script>
  <script>
    var vis_data = <%= safe_js_object @visualization.to_hash.to_json %>;
    var user_data = <%= safe_js_object current_user.data({ show_api_calls: false }).to_json %>;
    var config = <%= safe_js_object frontend_config %>;
    var map_data = <%= safe_js_object @visualization.map.public_values.to_json %>;
    var basemaps = <%=raw Cartodb.config[:basemaps].present? ? Cartodb.config[:basemaps].to_json.html_safe: 'null' %>;
    var authTokens = <%= safe_js_object @auth_tokens.to_json %>;
  </script>

  <% content_for(:js) do %>
    <% if !@google_maps_query_string.blank? %>
      <%= insert_google_maps(@google_maps_query_string) %>
    <% end %>
    <%= editor_javascript_include_tag 'cdb.js','models.js', 'templates.js', 'templates_mustache.js', 'table.js', 'editor.js' %>
  <% end %>

  <div class="panes"></div>

app/views/admin/visualizations/track.html.erb
<!DOCTYPE html>
<html lang="en">
  <body>

  </body>
</html>